[project]
name = "bank-statement-converter"
version = "0.1.1"
description = "A collection of tools to convert Nigerian bank statements in pdf format into a structured format."
requires-python = ">=3.12"
dependencies = [
    "camelot-py>=1.0.0",
    "notebook>=7.4.3"
]
